### PR TITLE
well.. this is NOT working.. see text and message in forums

### PR DESCRIPTION
**Pull request by dredhorse**
Hi,

just if you feel like it trying to fix it..

Atm the Ftp queue is empty to I don't know if it is working.. an upgrade process for the config is also still missing.

and for whatever reason the debug: true setting in the config doesn't work anymore (I think since I upgraded the version of the plugin to 0.5.6

### CODE REVIEW

**Comment by dredhorse** [comment]
ok... I move the version back to 0.5.5, also the config update is missing atm.

It looks like it works, I can't test though as it is not allowing usernames in the style of user@domain.org which are used by ftp Servers running on shared hosting.

**Comment by dredhorse** [comment]
ok.. updated the version to 0.5.6.. it works fine..

I hope I didn't forget anything, feel free to make changes if needed.

**Comment by dredhorse** [comment]
included plugin

**Comment by ltguide** [comment]
Can you test ftp with 0.5.8? I encoded the username and it worked with ltguide@blah.com on FileZilla's server.

**Comment by dredhorse** [comment]
I will... code looks nice.. better than my quick hack..

**Comment by ltguide** [comment]
It's almost the same changes, except I combined dropbox and ftp support into TaskUpload. I'm just not a fan of using big libraries. The downside to the way I did it is the plugin can't make the directory structure. I'm going to wait and see if people complain.

**Comment by dredhorse** [comment]
well if you document the structure which is needed it would be just more work... otherwise it will be for sure something to complain on as people expect it to just work..

**Pull request closed without merging**
