### PR TITLE
added Base and removed CraftBukkit-Base edited readme

### PR DESCRIPTION
**Pull request by Crazy-Uncle-Harris**
deleted the empty folder that had the CraftBukkit-Base code "in" it, it was empty
created Base folder and stuck the CraftBukkit-Base code into that instead
Updated the Readme.md file to show these changes.

``` computerdude5000
```

### CODE REVIEW

**Comment by ltguide** [comment]
It's not supposed to be empty actually. I haven't tried to clone it myself. On my end, I used 'git submodule' to add base.

I think it is: git submodule add git@github.com:ltguide/CraftBukkit-Base.git

**Comment by ltguide** [comment]
If that works, the readme just needs to be updated.

**Comment by Crazy-Uncle-Harris** [comment]
that might be why cause all it shows up for me is CraftBukkit-Base and it is unclickable its just black and when you download using ltguide/CraftBukkit-Minebackup.git it downloads the folder with nothing in it

**Comment by Crazy-Uncle-Harris** [comment]
well got an idea for github live pull feed's like facebook retime comments cause I didn't see your comment about the readme needing to be updated and I beleive i did up date the readme to reflect the changes.

**Comment by ltguide** [comment]
Oh, I meant: all that's needed is to update the readme to explain that the base folder is fetched with the submodule command.

**Comment by Crazy-Uncle-Harris** [comment]
ah true

**Comment by keyz182** [comment]
Hi guys. It seems you've not added your .gitmodules file. This keeps the mapping betweek the folder and submodule.

If I 
`git rm CraftBukkit-Base`
then
`git submodule add git@github.com:ltguide/CraftBukkit-Base.git`

My .gitmodules looks like:

`[submodule "CraftBukkit-Base"]
    path = CraftBukkit-Base
    url = git@github.com:ltguide/CraftBukkit-Base.git`

**Comment by Crazy-Uncle-Harris** [comment]
what the heck is a .gitmodule
file lol

**Comment by keyz182** [comment]
When you do 
`git submodule add <<bleh>>`
Git adds a file named ".gitmodule" to keep track of the submodules.

Until it's fixed in this repo, just run the following:
`rm -r CraftBukkit-Base 
git rm CraftBukkit-Base
git submodule add git@github.com:ltguide/CraftBukkit-Base.git
git submodule update`

Then the CraftBukkit-Base should be automagically filled.

The .gitmodules file should be in the repo. Someone cloning the repo should only need to run

`git submodule init
git submodule update`

**Comment by Crazy-Uncle-Harris** [comment]
ah

**Comment by keyz182** [comment]
I've submitted a pull request to fix by adding the .gitmodules file (Pull Request #41).

**Pull request closed without merging**
